/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ParkingSystem;
import javax.swing.JOptionPane;
import java.util.Arrays;

/**
 *
 * @author PRABHANJAN
 */
public class NewUserForm extends javax.swing.JFrame {
    DatabaseConnection cn = new DatabaseConnection();
    /**
     * Creates new form NewUserForm
     */
    public NewUserForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnewuser = new javax.swing.JLabel();
        newuserpanel = new javax.swing.JPanel();
        lblinputusername = new javax.swing.JLabel();
        txtinputusername = new javax.swing.JTextField();
        lblinputplace = new javax.swing.JLabel();
        cmbinputplace = new javax.swing.JComboBox<>();
        lblinputplacename = new javax.swing.JLabel();
        txtinputplacename = new javax.swing.JTextField();
        lblinputdestination = new javax.swing.JLabel();
        txtinputdestination = new javax.swing.JTextField();
        lblinputpassword = new javax.swing.JLabel();
        txtinputpassword = new javax.swing.JPasswordField();
        lblreinputpassword = new javax.swing.JLabel();
        txtreinputpassword = new javax.swing.JPasswordField();
        btnregister = new javax.swing.JButton();
        btninputformcancle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New User");
        setBackground(new java.awt.Color(204, 204, 255));
        setName("newuserframe"); // NOI18N

        lblnewuser.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        lblnewuser.setText("  NEW USER");

        newuserpanel.setBackground(new java.awt.Color(204, 204, 255));
        newuserpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        lblinputusername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblinputusername.setText("User Name                                       :");

        txtinputusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtinputusernameFocusLost(evt);
            }
        });

        lblinputplace.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblinputplace.setText("Enter Place name                            :");

        cmbinputplace.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-----Select----->", "School", "College", "Goverment sector", "Mall" }));
        cmbinputplace.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbinputplaceFocusLost(evt);
            }
        });

        lblinputplacename.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblinputplacename.setText("Select Sector                                   :");

        txtinputplacename.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtinputplacenameFocusLost(evt);
            }
        });

        lblinputdestination.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblinputdestination.setText("Enter your favourite Destination  :");

        txtinputdestination.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtinputdestinationFocusLost(evt);
            }
        });

        lblinputpassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblinputpassword.setText("Enter Password                                :");

        txtinputpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtinputpasswordFocusLost(evt);
            }
        });

        lblreinputpassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblreinputpassword.setText("Re-enter Password                         :");

        txtreinputpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtreinputpasswordFocusLost(evt);
            }
        });

        btnregister.setText("Register");
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });

        btninputformcancle.setText("Cancle");
        btninputformcancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninputformcancleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newuserpanelLayout = new javax.swing.GroupLayout(newuserpanel);
        newuserpanel.setLayout(newuserpanelLayout);
        newuserpanelLayout.setHorizontalGroup(
            newuserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newuserpanelLayout.createSequentialGroup()
                .addGroup(newuserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(newuserpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(newuserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(newuserpanelLayout.createSequentialGroup()
                                .addComponent(lblinputdestination)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtinputdestination))
                            .addGroup(newuserpanelLayout.createSequentialGroup()
                                .addGroup(newuserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblinputplace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblinputusername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(newuserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbinputplace, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtinputusername, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtinputplacename, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(newuserpanelLayout.createSequentialGroup()
                                .addComponent(lblinputpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtinputpassword))
                            .addGroup(newuserpanelLayout.createSequentialGroup()
                                .addComponent(lblreinputpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtreinputpassword))))
                    .addGroup(newuserpanelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btninputformcancle, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnregister, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(newuserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(newuserpanelLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(lblinputplacename)
                    .addContainerGap(249, Short.MAX_VALUE)))
        );
        newuserpanelLayout.setVerticalGroup(
            newuserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newuserpanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(newuserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinputusername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtinputusername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(cmbinputplace, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(newuserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinputplace, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtinputplacename, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(newuserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinputdestination, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtinputdestination, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(newuserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinputpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtinputpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(newuserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblreinputpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtreinputpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(newuserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregister, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btninputformcancle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(newuserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(newuserpanelLayout.createSequentialGroup()
                    .addGap(129, 129, 129)
                    .addComponent(lblinputplacename, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(340, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(lblnewuser, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(newuserpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblnewuser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(newuserpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(626, 661));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtinputusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtinputusernameFocusLost
        // TODO add your handling code here:
        if(txtinputusername.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(NewUserForm.this, "Please enter Username");
            //txtinputusername.grabFocus();
            return;
        }
    }//GEN-LAST:event_txtinputusernameFocusLost

    private void cmbinputplaceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbinputplaceFocusLost
        // TODO add your handling code here:
        if(cmbinputplace.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(NewUserForm.this, "Please Select Sector");
            return;
        }
    }//GEN-LAST:event_cmbinputplaceFocusLost

    private void txtinputplacenameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtinputplacenameFocusLost
        // TODO add your handling code here:
        if(txtinputplacename.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(NewUserForm.this, "Please enter Place");
            //txtinputplacename.grabFocus();
            return;
        }
    }//GEN-LAST:event_txtinputplacenameFocusLost

    private void txtinputdestinationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtinputdestinationFocusLost
        // TODO add your handling code here:
        if(txtinputdestination.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(NewUserForm.this, "Please enter Destination");
            //txtinputdestination.grabFocus();
            return;
        }
    }//GEN-LAST:event_txtinputdestinationFocusLost

    private void txtinputpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtinputpasswordFocusLost
        // TODO add your handling code here:
        if(txtinputpassword.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(NewUserForm.this, "Please enter Password");
            //txtinputpassword.grabFocus();
            return;
        }
    }//GEN-LAST:event_txtinputpasswordFocusLost

    private void txtreinputpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtreinputpasswordFocusLost
        // TODO add your handling code here:
        if(txtreinputpassword.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(NewUserForm.this, "Please re enter password");
            //txtreinputpassword.grabFocus();
            return;
        }
    }//GEN-LAST:event_txtreinputpasswordFocusLost

    private int[] getValues(String sector){
        int[] rupess = new int[2];
        if(sector.toLowerCase().equals("school") || sector.toLowerCase().equals("college") ){
            rupess[0] = 5;
            rupess[1] = 10;
        }
        if(sector.toLowerCase().equals("goverment sector")){
            rupess[0] = 10;
            rupess[1] = 20;
        }
        if(sector.toLowerCase().equals("mall")){
            rupess[0] = 20;
            rupess[1] = 30;
        }
        return rupess;
    }
    
    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        // TODO add your handling code here:
        String username = txtinputusername.getText();
        String sector = cmbinputplace.getSelectedItem().toString();
        //System.out.println(sector);
        String place = txtinputplacename.getText();
        String destination = txtinputdestination.getText();
        String password = txtinputpassword.getText();
        String repassword = txtreinputpassword.getText();
        int[] rupess = getValues(sector);
        //System.out.println(rs[0] + " " + rs[1]);
        
        if(!password.equals(repassword)){
            JOptionPane.showMessageDialog(NewUserForm.this, "Password not matched");
            return;
        }
        
        if(cn.insertAdminData(username, sector, place, destination, rupess[0], rupess[1], password)){
            this.dispose();
            new Log_In_Window().setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(NewUserForm.this, "Sorry Data Can not added");
        }
        
    }//GEN-LAST:event_btnregisterActionPerformed

    private void btninputformcancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninputformcancleActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new FirstWindow().setVisible(true);
    }//GEN-LAST:event_btninputformcancleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btninputformcancle;
    private javax.swing.JButton btnregister;
    private javax.swing.JComboBox<String> cmbinputplace;
    private javax.swing.JLabel lblinputdestination;
    private javax.swing.JLabel lblinputpassword;
    private javax.swing.JLabel lblinputplace;
    private javax.swing.JLabel lblinputplacename;
    private javax.swing.JLabel lblinputusername;
    private javax.swing.JLabel lblnewuser;
    private javax.swing.JLabel lblreinputpassword;
    private javax.swing.JPanel newuserpanel;
    private javax.swing.JTextField txtinputdestination;
    private javax.swing.JPasswordField txtinputpassword;
    private javax.swing.JTextField txtinputplacename;
    private javax.swing.JTextField txtinputusername;
    private javax.swing.JPasswordField txtreinputpassword;
    // End of variables declaration//GEN-END:variables
}
