/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ParkingSystem;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;

/**
 *
 * @author prabhanjan
 */
public class ReciptFrame extends javax.swing.JFrame {
    DatabaseConnection dc = new DatabaseConnection();
    /**
     * Creates new form ReciptFrame
     */
    public ReciptFrame(String...data) {
        initComponents();
        lblTitle.setText(dc.getParkingName());
        lblbikeNumber.setText(lblbikeNumber.getText()+"   "+data[0]);
        lblparkedtime.setText(lblparkedtime.getText()+"   "+data[3]);
        lblParkedDate.setText(lblParkedDate.getText()+"   "+data[2]);
        lblRupess.setText(lblRupess.getText()+"   "+data[1]);
        
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        printingpanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblbikeNumber = new javax.swing.JLabel();
        lblparkedtime = new javax.swing.JLabel();
        lblParkedDate = new javax.swing.JLabel();
        lblRupess = new javax.swing.JLabel();
        lblstamp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recipt");
        setBackground(new java.awt.Color(204, 204, 255));
        setName("reciptFrame"); // NOI18N

        printingpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printingpanelMouseClicked(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblTitle.setText("         ");

        lblbikeNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblbikeNumber.setText("Vehicle Number    :  ");

        lblparkedtime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblparkedtime.setText("Vehicle Parked at   :");

        lblParkedDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblParkedDate.setText("Parked Date  :");

        lblRupess.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRupess.setText("Rupees  :");

        lblstamp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblstamp.setText("Stamp / Sign");

        javax.swing.GroupLayout printingpanelLayout = new javax.swing.GroupLayout(printingpanel);
        printingpanel.setLayout(printingpanelLayout);
        printingpanelLayout.setHorizontalGroup(
            printingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printingpanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(printingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblbikeNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(printingpanelLayout.createSequentialGroup()
                        .addGroup(printingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblparkedtime, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(printingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblRupess, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblParkedDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)))
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printingpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(printingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printingpanelLayout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printingpanelLayout.createSequentialGroup()
                        .addComponent(lblstamp, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        printingpanelLayout.setVerticalGroup(
            printingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printingpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblbikeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblparkedtime, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblParkedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblRupess, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(lblstamp, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(printingpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(printingpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printingpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printingpanelMouseClicked
        // TODO add your handling code here:
        Printdata();
    }//GEN-LAST:event_printingpanelMouseClicked

    /**
     * @param args the command line arguments
     */
     private void Printdata(){
         PrinterJob job = PrinterJob.getPrinterJob();
         job.setJobName("Parking System");
         
         job.setPrintable(new Printable(){
             public int print(Graphics pg,PageFormat pf,int pageNum){
                 if(pageNum>0){
                     return Printable.NO_SUCH_PAGE;
                 }
                 
                 Graphics2D g2 = (Graphics2D)pg;
                 g2.translate(pf.getImageableX(), pf.getImageableY());
                 g2.scale(0.24,0.24);
                 
                 printingpanel.paint(g2);
                 return Printable.PAGE_EXISTS;
             }
         });
         
         boolean ok = job.printDialog();
         if(ok){
             try{
                 job.print();
             }catch(Exception ex){
                 JOptionPane.showMessageDialog(ReciptFrame.this,"Can not print");
             }
         }
     }
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReciptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReciptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReciptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReciptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReciptFrame("null").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblParkedDate;
    private javax.swing.JLabel lblRupess;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblbikeNumber;
    private javax.swing.JLabel lblparkedtime;
    private javax.swing.JLabel lblstamp;
    private javax.swing.JPanel printingpanel;
    // End of variables declaration//GEN-END:variables
}
